services:
  node:
    ports:
      - "9910:9910"

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - DATABASE_URL=postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB_NAME}
      - PORT=${PORT}
      - OPEN_AI_KEY=${OPEN_AI_KEY}
    depends_on:
      - db

    volumes:
      - .:/app
    command: npm run dev

  db:
    image: postgres:15
    hostname: localhost
    container_name: container-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    restart: unless-stopped

volumes:
  postgres-data:
