name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker compose image
      run: docker compose build 

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.10.0
